import requests

colleges=[
["Amherst", "https://www.amherst.edu/system/files/media/Amherst_A_Outlined-Purple-Stomp-400px.png&__=1518819354"],
["Barnard", "https://barnard.edu/sites/default/files/styles/top_news_view__325x240_/public/barnard-b-blue-square-01.png?itok=tjdz2rnb"],
["Bates", "http://www.skyedesignstudios.com/images/portfolio/marks/bates-college-secondary-2_143.png"],
["Boston College", "https://upload.wikimedia.org/wikipedia/en/thumb/9/96/Boston_College_Eagles_logo.svg/1200px-Boston_College_Eagles_logo.svg.png"],
["Boston University", "https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Boston_University_Terriers_logo.svg/1200px-Boston_University_Terriers_logo.svg.png"],
["Bowdoin", "http://livestats.prestosports.com/logos/69.png"],
["Brown", "http://www.dam.brown.edu/people/hdong/images/BrownU.png"],
["Bucknell", "https://www.bucknell.edu/Images/Depts/Communication/printables/printable-bucknellB-large.png"],
["Caltech", "http://identity.caltech.edu/site_images/447-caltech_seal-200w.png"],
["Carleton", "https://s3.amazonaws.com/file.imleagues/Images/Schools/Uploaded/201604/20164299389.png"],
["Carnegie Mellon", "https://www.cmu.edu/marcom/brand-standards/images/red-seal-greater-than-two-inches-min.png"],
["Chapman", "https://brand.chapman.edu/wp-content/uploads/2015/01/cu-seal.jpg"],
["Claremont Mckenna", "http://img.new.livestream.com/accounts/000000000005a1af/0bb7bb7d-f7e6-4a3c-aa36-4ffb044e0be4.png"],
["Colgate", "https://static1.squarespace.com/static/59bc0ff818b27dff8196865f/59bc14ae37c581cd2123f9cb/5a1e40fa652dea2e1af43a14/1511932159645/ColgateUniversity_large.jpg?format=1000w"],
["Columbia", "http://www.stickpng.com/assets/images/5842f74da6515b1e0ad75b26.png"],
["Cornell", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/cornell.png"],
["Dartmouth", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/dartmouth.png"],
["Davidson", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/davidson.png"],
["Duke", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/duke.png"],
["Emory", "https://scholarblogs.emory.edu/chemistry/files/2017/04/cropped-emory-shield-1.png"],
["Georgetown", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/georgetown.png"],
["Harvard", "https://www.harvard.edu/sites/default/files/user13/harvard_shield_wreath.png"],
["Haverford", "https://blogs.haverford.edu/haverblog/files/2014/06/Haverford_Cupola_Black_haverblog-279x300.png"],
["Indiana", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/indiana.png"],
["Johns Hopkins", "https://brand.jhu.edu/assets/uploads/sites/5/2014/06/university.shield.small_.blue_.png"],
["Kenyon", "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Kenyon_College_seal.svg/1200px-Kenyon_College_seal.svg.png"],
["Loyola Marymount", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Loyola_Marymount_Lions_logo.svg/1200px-Loyola_Marymount_Lions_logo.svg.png"],
["MIT", "https://specials-images.forbesimg.com/imageserve/557f394de4b017853ecec0bd/200x200.jpg?fit=scale&background=000000"],
["Middlebury", "https://www.thewrap.com/wp-content/uploads/2017/03/middlebury_logo_detail.png"],
["NYU", "http://cusp.nyu.edu/wp-content/uploads/2018/03/cropped-Untitled-1.png"],
["Northwestern", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/northwestern.png"],
["Pomona", "https://www.pomona.edu/sites/default/files/styles/inset/public/images/insets/collegemark-standalone.jpg?itok=_1cSWbCi"],
["Princeton", "https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Princeton_shield.svg/1200px-Princeton_shield.svg.png"],
["Rice", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/rice.png"],
["Santa Clara", "http://content.sportslogos.net/logos/34/829/full/ph901x95dj6snenmpb7h.gif"],
["SMU", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/smu.png"],
["Stanford", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/stanford.png"],
["Swarthmore", "https://swarthmoreathletics.com/common/controls/image_handler.aspx?thumb_id=0&image_path=/images/2018/7/24/SwatGarnet_red_better_justS.png"],
["Trinity", "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Trinity_College_Connecticut_Seal.svg/1200px-Trinity_College_Connecticut_Seal.svg.png"],
["Tufts", "https://seeklogo.com/images/T/tufts-university-logo-C22B1DB618-seeklogo.com.png"],
["Tulane", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/tulane.png"],
["UC Berkeley", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/california.png"],
["UC Davis", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/ucDavis.png"],
["UCLA", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/ucla.png"],
["UC San Diego", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/sanDiego.png"],
["U Chicago", "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/University_of_Chicago_shield.svg/1200px-University_of_Chicago_shield.svg.png"],
["Boulder", "https://upload.wikimedia.org/wikipedia/commons/d/d4/Colorado_Buffs_alternate_logo.png"],
["University of Miami", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/miami.png"],
["Michigan", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/michigan.png"],
["Notre Dame", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/notreDame.png"],
["Penn", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/UPenn_shield_with_banner.svg/2000px-UPenn_shield_with_banner.svg.png"],
["Richmond", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/richmond.png"],
["USC", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/USC_Trojans_logo.svg/244px-USC_Trojans_logo.svg.png"],
["Texas", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Texas_Longhorns_logo.svg/2000px-Texas_Longhorns_logo.svg.png"],
["Virginia", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/virginia.png"],
["Wisconsin", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/wisconsin.png"],
["Vanderbilt", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/vanderbilt.png"],
["Vassar", "https://connect.vassar.edu/s/1654/images/gid2/editor/a_headers/vc_logos/vc-logo-rose_gray.jpg"],
["Wake Forest", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/wakeForest.png"],
["Wash U", "https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/WashU_St._Louis_seal.svg/1200px-WashU_St._Louis_seal.svg.png"],
["Wesleyan", "https://s3.amazonaws.com/rm3.photos.prod.readmedia.com/brandings/37825/medium/main_w_500x500.jpg?2017"],
["Williams", "https://s3-us-west-2.amazonaws.com/uw-s3-cdn/wp-content/uploads/sites/98/2014/09/07212546/W-Logo_RegistrationMark_Purple_2685_HEX.png"],
["Yale", "https://raw.githubusercontent.com/abrelsfo/sportsJSON/master/collegeFootball/logos/yale.png"]
]
for x in colleges:

    r = requests.get(x[1], allow_redirects=True)
    open('{}.png'.format(x[0]), 'wb').write(r.content)
